name: Generate Christmas Tree

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run Christmas Tree Script
      run: |
        export PYTHONPATH=${{github.workspace}}
        python ./tests_/common_/runners_/htmlRunners_/regressionRunner.py

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: christmas-tree-tests-report
        path: reports_/report_*.html
